steps:
  # Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/hackathon-ecom-server:$COMMIT_SHA'
      - '-t'
      - 'gcr.io/$PROJECT_ID/hackathon-ecom-server:latest'
      - '.'
    dir: 'server'

  # Push the Docker image to Google Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/hackathon-ecom-server:$COMMIT_SHA'

  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/hackathon-ecom-server:latest'

  # Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'hackathon-ecom-server'
      - '--image'
      - 'gcr.io/$PROJECT_ID/hackathon-ecom-server:$COMMIT_SHA'
      - '--region'
      - 'asia-southeast1'  # Change to your preferred region
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--memory'
      - '512Mi'
      - '--cpu'
      - '1'
      - '--timeout'
      - '300'
      - '--max-instances'
      - '10'
      - '--set-env-vars'
      - 'NODE_ENV=production'

# Store images in Google Container Registry
images:
  - 'gcr.io/$PROJECT_ID/hackathon-ecom-server:$COMMIT_SHA'
  - 'gcr.io/$PROJECT_ID/hackathon-ecom-server:latest'

# Build timeout
timeout: 1200s

options:
  machineType: 'N1_HIGHCPU_8'
